//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashpointSecurePlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashpointSecurePlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActiveX Control failed to install..
        /// </summary>
        internal static string ActiveXControlInstallFailed {
            get {
                return ResourceManager.GetString("ActiveXControlInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActiveX Control failed to uninstall..
        /// </summary>
        internal static string ActiveXControlUninstallFailed {
            get {
                return ResourceManager.GetString("ActiveXControlUninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address ({0}) wasn&apos;t understood. Please report this bug..
        /// </summary>
        internal static string AddressNotUnderstood {
            get {
                return ResourceManager.GetString("AddressNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of Flashpoint Secure Player is preventing the Modifications from being activated..
        /// </summary>
        internal static string AnotherInstanceCausingInterference {
            get {
                return ResourceManager.GetString("AnotherInstanceCausingInterference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as Administrator User.
        /// </summary>
        internal static string AsAdministratorUser {
            get {
                return ResourceManager.GetString("AsAdministratorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration failed to load.
        ///Please ensure Flashpoint is not corrupted, was extracted correctly, and is not running from OneDrive or a network drive..
        /// </summary>
        internal static string ConfigurationFailedLoad {
            get {
                return ResourceManager.GetString("ConfigurationFailedLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This curation is missing a template name..
        /// </summary>
        internal static string CurationMissingTemplateName {
            get {
                return ResourceManager.GetString("CurationMissingTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A game file is being downloaded..
        /// </summary>
        internal static string DownloadingGameFile {
            get {
                return ResourceManager.GetString("DownloadingGameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Environment Variables failed..
        /// </summary>
        internal static string EnvironmentVariablesFailed {
            get {
                return ResourceManager.GetString("EnvironmentVariablesFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a Custom Security Manager..
        /// </summary>
        internal static string FailedCreateCustomSecurityManager {
            get {
                return ResourceManager.GetString("FailedCreateCustomSecurityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get the Parent Process EXE File Name..
        /// </summary>
        internal static string FailedGetParentProcessEXEFileName {
            get {
                return ResourceManager.GetString("FailedGetParentProcessEXEFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flashpoint Proxy could not be enabled..
        /// </summary>
        internal static string FlashpointProxyNotEnabled {
            get {
                return ResourceManager.GetString("FlashpointProxyNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashpoint Secure Player.
        /// </summary>
        internal static string FlashpointSecurePlayer {
            get {
                return ResourceManager.GetString("FlashpointSecurePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game failed to launch {0}..
        /// </summary>
        internal static string GameFailedLaunch {
            get {
                return ResourceManager.GetString("GameFailedLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game files ({0}) are missing.
        ///Please ensure Flashpoint is not corrupted, was extracted correctly, and is not running from OneDrive or a network drive..
        /// </summary>
        internal static string GameIsMissingFiles {
            get {
                return ResourceManager.GetString("GameIsMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is not a valid ActiveX Control..
        /// </summary>
        internal static string GameNotActiveXControl {
            get {
                return ResourceManager.GetString("GameNotActiveXControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game was not curated correctly. Please report this bug..
        /// </summary>
        internal static string GameNotCuratedCorrectly {
            get {
                return ResourceManager.GetString("GameNotCuratedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Job Object could not be created. Is your Windows Version new enough? Flashpoint only supports Windows 7, Windows 8, Windows 8.1, and Windows 10..
        /// </summary>
        internal static string JobObjectNotCreated {
            get {
                return ResourceManager.GetString("JobObjectNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game will not work unless run {0}. Do you want to launch it {0}?
        ///If you choose No, the application will exit..
        /// </summary>
        internal static string LaunchGame {
            get {
                return ResourceManager.GetString("LaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game was selected to start, so the application is exiting..
        /// </summary>
        internal static string NoGameSelected {
            get {
                return ResourceManager.GetString("NoGameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mode was selected..
        /// </summary>
        internal static string NoModeSelected {
            get {
                return ResourceManager.GetString("NoModeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Old CPU Simulator failed. The Target Rate may be invalid..
        /// </summary>
        internal static string OldCPUSimulatorFailed {
            get {
                return ResourceManager.GetString("OldCPUSimulatorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Flashpoint Launcher by opening the Start Flashpoint shortcut in the Flashpoint folder..
        /// </summary>
        internal static string OpenFlashpointLauncher {
            get {
                return ResourceManager.GetString("OpenFlashpointLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process {0} causes a compatibility conflict with this game. Please close it to continue..
        /// </summary>
        internal static string ProcessCompatibilityConflict {
            get {
                return ResourceManager.GetString("ProcessCompatibilityConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process failed to start..
        /// </summary>
        internal static string ProcessFailedStart {
            get {
                return ResourceManager.GetString("ProcessFailedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry Backup cannot start because another one is already in progress..
        /// </summary>
        internal static string RegistryBackupAlreadyInProgress {
            get {
                return ResourceManager.GetString("RegistryBackupAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry Backup failed..
        /// </summary>
        internal static string RegistryBackupFailed {
            get {
                return ResourceManager.GetString("RegistryBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Registry Backup is in progress. Please do not turn off your computer..
        /// </summary>
        internal static string RegistryBackupInProgress {
            get {
                return ResourceManager.GetString("RegistryBackupInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry Backup cannot be stopped because no Registry Backup was in progress..
        /// </summary>
        internal static string RegistryBackupNotInProgress {
            get {
                return ResourceManager.GetString("RegistryBackupNotInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry Backup was successful..
        /// </summary>
        internal static string RegistryBackupWasSuccessful {
            get {
                return ResourceManager.GetString("RegistryBackupWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required components are loading. Please do not turn off your computer..
        /// </summary>
        internal static string RequiredComponentsAreLoading {
            get {
                return ResourceManager.GetString("RequiredComponentsAreLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required components are unloading. Please do not turn off your computer..
        /// </summary>
        internal static string RequiredComponentsAreUnloading {
            get {
                return ResourceManager.GetString("RequiredComponentsAreUnloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown process is causing a compatibility conflict with this game, and the application cannot continue..
        /// </summary>
        internal static string UnknownProcessCompatibilityConflict {
            get {
                return ResourceManager.GetString("UnknownProcessCompatibilityConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the Flashpoint Launcher to select a game to start..
        /// </summary>
        internal static string UseFlashpointLauncher {
            get {
                return ResourceManager.GetString("UseFlashpointLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Windows Version is too old for Flashpoint Secure Player. Flashpoint supports Windows 7, Windows 8, Windows 8.1, and Windows 10..
        /// </summary>
        internal static string WindowsVersionTooOld {
            get {
                return ResourceManager.GetString("WindowsVersionTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Compatibility Settings.
        /// </summary>
        internal static string WithCompatibilitySettings {
            get {
                return ResourceManager.GetString("WithCompatibilitySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Old CPU Simulator.
        /// </summary>
        internal static string WithOldCPUSimulator {
            get {
                return ResourceManager.GetString("WithOldCPUSimulator", resourceCulture);
            }
        }
    }
}
