//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashpointSecurePlayer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashpointSecurePlayer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActiveX Control is unable to be installed..
        /// </summary>
        internal static string ActiveXControlUnableToInstall {
            get {
                return ResourceManager.GetString("ActiveXControlUnableToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActiveX Control is unable to be uninstalled..
        /// </summary>
        internal static string ActiveXControlUnableToUninstall {
            get {
                return ResourceManager.GetString("ActiveXControlUnableToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address ({0}) wasn&apos;t understood. Please report this bug..
        /// </summary>
        internal static string AddressNotUnderstood {
            get {
                return ResourceManager.GetString("AddressNotUnderstood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Template could not be activated.
        ///Another instance of Flashpoint Secure Player is preventing the Template from being activated..
        /// </summary>
        internal static string AnotherInstancePreventingTemplate {
            get {
                return ResourceManager.GetString("AnotherInstancePreventingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to as an Administrator User.
        /// </summary>
        internal static string AsAdministratorUser {
            get {
                return ResourceManager.GetString("AsAdministratorUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration is unable to be loaded.
        ///Please ensure Flashpoint is not corrupted, was extracted correctly, and is not running from OneDrive or a network drive..
        /// </summary>
        internal static string ConfigurationUnableToLoad {
            get {
                return ResourceManager.GetString("ConfigurationUnableToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This curation is missing a template name..
        /// </summary>
        internal static string CurationMissingTemplateName {
            get {
                return ResourceManager.GetString("CurationMissingTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Environment Variables encountered a problem..
        /// </summary>
        internal static string EnvironmentVariablesProblem {
            get {
                return ResourceManager.GetString("EnvironmentVariablesProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Environment Variables timed out..
        /// </summary>
        internal static string EnvironmentVariablesTimeout {
            get {
                return ResourceManager.GetString("EnvironmentVariablesTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Flashpoint Proxy could not be enabled..
        /// </summary>
        internal static string FlashpointProxyNotEnabled {
            get {
                return ResourceManager.GetString("FlashpointProxyNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flashpoint Secure Player.
        /// </summary>
        internal static string FlashpointSecurePlayer {
            get {
                return ResourceManager.GetString("FlashpointSecurePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will force the deletion of the modification from your system. You should not do this unless instructed to by Flashpoint staff. Continue?.
        /// </summary>
        internal static string ForceDeleteAllWarning {
            get {
                return ResourceManager.GetString("ForceDeleteAllWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game is downloading..
        /// </summary>
        internal static string GameDownloading {
            get {
                return ResourceManager.GetString("GameDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game files ({0}) are missing.
        ///Please ensure Flashpoint is not corrupted, was extracted correctly, and is not running from OneDrive or a network drive..
        /// </summary>
        internal static string GameIsMissingFiles {
            get {
                return ResourceManager.GetString("GameIsMissingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is not a valid ActiveX Control..
        /// </summary>
        internal static string GameNotActiveXControl {
            get {
                return ResourceManager.GetString("GameNotActiveXControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game was not curated correctly. Please report this bug..
        /// </summary>
        internal static string GameNotCuratedCorrectly {
            get {
                return ResourceManager.GetString("GameNotCuratedCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game is unable to launch {0}..
        /// </summary>
        internal static string GameUnableToLaunch {
            get {
                return ResourceManager.GetString("GameUnableToLaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ActiveX Control Install Status will be ignored. The ActiveX Import may not work as intended..
        /// </summary>
        internal static string IgnoreActiveXControlInstallFailureWarning {
            get {
                return ResourceManager.GetString("IgnoreActiveXControlInstallFailureWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Job Object could not be created. Is your Windows Version new enough? Flashpoint only supports Windows 7, Windows 8, Windows 8.1, and Windows 10..
        /// </summary>
        internal static string JobObjectNotCreated {
            get {
                return ResourceManager.GetString("JobObjectNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This game will not work unless it is run {0}. Do you want to launch it {0}?
        ///If you choose No, the application will exit..
        /// </summary>
        internal static string LaunchGame {
            get {
                return ResourceManager.GetString("LaunchGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Modifications were unable to load because an Import was in progress..
        /// </summary>
        internal static string ModificationsUnableToLoadImport {
            get {
                return ResourceManager.GetString("ModificationsUnableToLoadImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No game was selected to start, so the application is exiting..
        /// </summary>
        internal static string NoGameSelected {
            get {
                return ResourceManager.GetString("NoGameSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mode was selected..
        /// </summary>
        internal static string NoModeSelected {
            get {
                return ResourceManager.GetString("NoModeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CPU&apos;s clock speed could not be determined..
        /// </summary>
        internal static string OCS_CPUSpeedNotDetermined {
            get {
                return ResourceManager.GetString("OCS_CPUSpeedNotDetermined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must not run multiple instances of Old CPU Simulator..
        /// </summary>
        internal static string OCS_NoMultipleInstances {
            get {
                return ResourceManager.GetString("OCS_NoMultipleInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The old CPU could not be simulated..
        /// </summary>
        internal static string OCS_OldCPUNotSimulated {
            get {
                return ResourceManager.GetString("OCS_OldCPUNotSimulated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old CPU Simulator.
        /// </summary>
        internal static string OldCPUSimulator {
            get {
                return ResourceManager.GetString("OldCPUSimulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Old CPU Simulator encountered a problem. The Target Rate may be invalid..
        /// </summary>
        internal static string OldCPUSimulatorProblem {
            get {
                return ResourceManager.GetString("OldCPUSimulatorProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With Old CPU Simulator, the game may load slowly. Please wait for the game to load..
        /// </summary>
        internal static string OldCPUSimulatorSlow {
            get {
                return ResourceManager.GetString("OldCPUSimulatorSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Flashpoint Launcher by opening the Start Flashpoint shortcut in the Flashpoint folder..
        /// </summary>
        internal static string OpenFlashpointLauncher {
            get {
                return ResourceManager.GetString("OpenFlashpointLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process {0} causes a compatibility conflict with this game. Please close it to continue..
        /// </summary>
        internal static string ProcessCompatibilityConflict {
            get {
                return ResourceManager.GetString("ProcessCompatibilityConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process is unable to start..
        /// </summary>
        internal static string ProcessUnableToStart {
            get {
                return ResourceManager.GetString("ProcessUnableToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry State cannot be started because another one has already been started..
        /// </summary>
        internal static string RegistryStateAlreadyInProgress {
            get {
                return ResourceManager.GetString("RegistryStateAlreadyInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry State is being created. Please do not turn off your computer..
        /// </summary>
        internal static string RegistryStateInProgress {
            get {
                return ResourceManager.GetString("RegistryStateInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry State cannot be stopped because no Registry State has been started..
        /// </summary>
        internal static string RegistryStateNotInProgress {
            get {
                return ResourceManager.GetString("RegistryStateNotInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry State timed out..
        /// </summary>
        internal static string RegistryStateTimeout {
            get {
                return ResourceManager.GetString("RegistryStateTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry State is unable to be created..
        /// </summary>
        internal static string RegistryStateUnableToCreate {
            get {
                return ResourceManager.GetString("RegistryStateUnableToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Registry State was successfully created..
        /// </summary>
        internal static string RegistryStateWasSuccessful {
            get {
                return ResourceManager.GetString("RegistryStateWasSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required components are loading. Please do not turn off your computer..
        /// </summary>
        internal static string RequiredComponentsAreLoading {
            get {
                return ResourceManager.GetString("RequiredComponentsAreLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required components are unloading. Please do not turn off your computer..
        /// </summary>
        internal static string RequiredComponentsAreUnloading {
            get {
                return ResourceManager.GetString("RequiredComponentsAreUnloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create a Custom Security Manager..
        /// </summary>
        internal static string UnableToCreateCustomSecurityManager {
            get {
                return ResourceManager.GetString("UnableToCreateCustomSecurityManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get the Parent Process EXE File Name..
        /// </summary>
        internal static string UnableToGetParentProcessEXEFileName {
            get {
                return ResourceManager.GetString("UnableToGetParentProcessEXEFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set the Working Directory..
        /// </summary>
        internal static string UnableToSetWorkingDirectory {
            get {
                return ResourceManager.GetString("UnableToSetWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown process is causing a compatibility conflict with this game.
        ///The application cannot continue..
        /// </summary>
        internal static string UnknownProcessCompatibilityConflict {
            get {
                return ResourceManager.GetString("UnknownProcessCompatibilityConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This curation uses the Flash ActiveX Control. It may not work as intended in future Windows updates..
        /// </summary>
        internal static string UseFlashActiveXControlWarning {
            get {
                return ResourceManager.GetString("UseFlashActiveXControlWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use the Flashpoint Launcher to select a game to start..
        /// </summary>
        internal static string UseFlashpointLauncher {
            get {
                return ResourceManager.GetString("UseFlashpointLauncher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Windows Version is too old for Flashpoint Secure Player. Flashpoint supports Windows 7, Windows 8, Windows 8.1, and Windows 10..
        /// </summary>
        internal static string WindowsVersionTooOld {
            get {
                return ResourceManager.GetString("WindowsVersionTooOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Compatibility Settings.
        /// </summary>
        internal static string WithCompatibilitySettings {
            get {
                return ResourceManager.GetString("WithCompatibilitySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with Old CPU Simulator.
        /// </summary>
        internal static string WithOldCPUSimulator {
            get {
                return ResourceManager.GetString("WithOldCPUSimulator", resourceCulture);
            }
        }
    }
}
